version: '2'

services:

 gql:
  build: ../../BE/.
  image: gql:latest
  container_name: gql
  restart: always
  depends_on:
   - db
  links:
   - db
  ports:
   - 15000:80
  environment:
   NEO4J_HOST: db
   NEO4J_HTTP: 17474
   NEO4J_BOLT: 17687
   NEO4J_USER: neo4j
   NEO4J_PASS: osdf1
   FE_HOST: localhost

 db:
  image: neo4j:3.0
  container_name: db
  ports:
   - 17473:7473
   - 17474:7474
   - 17687:7687
  volumes:
   - "./data:/data"
  environment:
   NEO4J_AUTH: neo4j/osdf1
