version: '2'

services:

 GDC:
  build: ./GDC/.
  image: gdc_ui:latest
  depends_on:
   - OSDF
  ports:
   - "8080:80"
   - "3000:3000"
   - "3001:3001"
   - "9876:9876"

 OSDF:
  build: ./OSDF/.
  image: osdf_api:latest
  ports:
   - "5984:5984"
   - "9200:9200"
   - "9300:9300"

 ES:

 CDB:
