version: '2'

services:

 portal:
  build: ../../FE/.
  image: portal:latest
  container_name: portal
  restart: always
  depends_on:
   - gql
  links:
   - gql
  ports:
   - 13000:3000
   - 13001:3001
   - 19876:9876
  environment:
   GQL_HOST: gql
   GQL_PORT: 15000
  entrypoint:
   - python
   - /home/gdc/dp/start_portal.py

 gql:
  build: ../../BE/.
  image: gql:latest
  container_name: gql
  restart: always
  depends_on:
   - db
  links:
   - db
  ports:
   - 15000:80
  environment:
   NEO4J_HOST: db
   NEO4J_HTTP: 17474
   NEO4J_BOLT: 17687
   NEO4J_USER: neo4j
   NEO4J_PASS: osdf1
   FE_HOST: portal
   FE_PORT: 13000 

 db:
  image: neo4j:3.0
  container_name: db
  ports:
   - 17474:7474
   - 17687:7687
  volumes:
   - "./data:/data"
  environment:
   NEO4J_AUTH: neo4j/osdf1
